#Custom Archetype
!setname 0x10de Exodia Necross
!setname 0x9048 Number α
!setname 0x990 Injection Fairy
!setname 0x992 Guardragon
!setname 0x994 W Nebula
!setname 0x995 Star God
!setname 0x997 Stellarnova
!setname 0x999 Armada
!setname 0x1999	StArmada
!setname 0x2999	RoyArmada
!setname 0x3999	EisArmada
!setname 0x4999	OukArmada
!setname 0x5999	PolArmada
!setname 0x6999	ForzArmada
!setname 0x7999	SanctArmada
!setname 0x8999	SinoArmada

#Custom Counters
!counter 0x271 Blaze Counter
!counter 0x272 Honey Counter

#Victory Reasons
!victory 0x98 Victory by the effect of "Exxod, the Millennium Guard Incarnate"
!victory 0x99 Victory by the effect of "World Legacy Conclusion"


#System
!system 3399 Cannot be used as material
!system 3400 Send it to the GY during the End Phase
!system 3401 Link Summon (alternative procedure)
!system 3402 Equipped by its effect

